# Generated by Django 4.2.7 on 2025-10-07 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('capacidad_maxima', models.IntegerField(default=20, verbose_name='Capacidad Máxima')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Centro Operacional',
                'verbose_name_plural': 'Centros Operacionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contacto_principal', models.CharField(max_length=100, verbose_name='Contacto Principal')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('frecuencia_km', models.IntegerField(help_text='Cada cuántos km se debe realizar', verbose_name='Frecuencia (km)')),
                ('costo_estimado', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Costo Estimado')),
                ('tiempo_estimado_horas', models.IntegerField(verbose_name='Tiempo Estimado (horas)')),
                ('es_preventivo', models.BooleanField(default=True, verbose_name='¿Es Preventivo?')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('tipo_capacidad', models.CharField(choices=[('GC', 'Gran Capacidad'), ('MC', 'Mediana Capacidad')], default='MC', max_length=2, verbose_name='Tipo de Capacidad')),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='operativo', max_length=20, verbose_name='Estado')),
                ('kilometraje_actual', models.IntegerField(default=0, verbose_name='Kilometraje Actual')),
                ('numero_chasis', models.CharField(blank=True, max_length=50, verbose_name='Número de Chasis')),
                ('numero_motor', models.CharField(blank=True, max_length=50, verbose_name='Número de Motor')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/', verbose_name='Foto del Vehículo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('centro_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='flota.centrooperacional', verbose_name='Centro Operacional')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='preventivo', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridad')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_realizacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Realización')),
                ('kilometraje_programado', models.IntegerField(verbose_name='Kilometraje Programado')),
                ('costo_estimado', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Costo Estimado')),
                ('costo_real', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Costo Real')),
                ('tiempo_estimado_horas', models.IntegerField(default=4, verbose_name='Tiempo Estimado (horas)')),
                ('descripcion', models.TextField(verbose_name='Descripción del Trabajo')),
                ('observaciones_programacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.proveedor', verbose_name='Proveedor')),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.tipomantenimiento', verbose_name='Tipo de Mantenimiento')),
                ('usuario_programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_programados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Programó')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='flota.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
